### ISSUE TITLE
Incorrect syntax highlighting when comments contain backticks

### ISSUE THREAD

**Issue by stevchin** [worlpaker/go-syntax#16]
If a comment contains a pair of backticks, coloring of the text after the second backtick is no longer treated as a comment and will highlight syntax errors (sometimes over multiple lines).

![image](https://github.com/user-attachments/assets/90be70d6-c78d-40be-85bf-769d4b5f3a7b)

Not sure exactly when this started, but I'm pretty sure that it didn't have this issue in the past.

VS Code 1.92.0
Go 1.22.5

**Comment by worlpaker** [comment]
Thanks for reporting. Probably, it occurred in [v0.7.0](https://github.com/worlpaker/go-syntax/releases/tag/v0.7.0).

I've published a new version to address this issue.

Can you please install the latest version of [go-syntax](https://marketplace.visualstudio.com/items?itemName=furkanozalp.go-syntax) and try it?

**v0.7.7**
![test](https://github.com/user-attachments/assets/601af7d1-642a-4602-adca-b022f9a72df9)

**Comment by stevchin** [comment]
Just installed go-syntax 0.7.7 and looks like it fixes the issue - thanks for the quick fix!
