### ISSUE TITLE
return func breaks next func syntax highlighting

### ISSUE THREAD

**Issue by LionelJouin** [worlpaker/go-syntax#17]
Does this issue occur when all extensions are disabled?: Yes

From https://github.com/microsoft/vscode/issues/232142

- VS Code Version: 
- OS Version: Ubuntu 24.04.1 LTS

Steps to Reproduce:

1. Open VS Code (https://vscode.dev/)
2. Create a new tab and paste this:
```golang
func abc() func() int {
	return func() int {
		return 5
	}
}

var _ = b()(func() {
    fmt.Println("")
    fmt.Println("")
    fmt.Println("")
})

func b() func(...interface{}) bool {
    return func(...interface{}) bool {
        return true
    }
}
```
4. As you can see, `fmt.println("")` are green
![Image](https://github.com/user-attachments/assets/a6b6620f-86aa-4106-811d-13527d1f8179)
6. Replace with this code
```golang
var _ = b()(func() {
    fmt.Println("")
    fmt.Println("")
    fmt.Println("")
})

func b() func(...interface{}) bool {
    return func(...interface{}) bool {
        return true
    }
}

func abc() func() int {
	return func() int {
		return 5
	}
}
```
5. As you can see, `fmt.println("")` are no longer green
![Image](https://github.com/user-attachments/assets/e37b0eef-550b-4d32-a1b1-871fbc7c8f43)

I first saw this issue while opening this file: https://github.com/kubernetes/kubernetes/blob/v1.31.2/test/e2e/dra/dra.go
It happens with any theme.

It also breaks with only this:
```golang
func abc() func() {return nil}

var _ = (func() {
    fmt.Println("")
    fmt.Println("")
    fmt.Println("")
})
```

**Comment by worlpaker** [comment]
Thanks for reporting.

I've published a new version to fix this issue. Could you please install the latest version of [go-syntax](https://marketplace.visualstudio.com/items?itemName=furkanozalp.go-syntax) and try it?

**v0.7.9**
![example](https://github.com/user-attachments/assets/efca59f9-1816-4c45-9cbd-3e8ecd53186b)

**Comment by LionelJouin** [comment]
I tried it and it works great now, thank you.
