### ISSUE TITLE
Distinguish between var const referee

### ISSUE THREAD

**Issue by RelicOfTesla** [worlpaker/go-syntax#18]
```go
var aaa = 1  // color 1
var bbb = 2  // color 2
println(aaa) // color 1
println(bbb) // color 2
```

**Comment by worlpaker** [comment]
I was considering this as well, but TextMate has limitations. It will only highlight the constant when declaring a const.

I've published a new version to add this feature.

**v0.8.0**
![example](https://github.com/user-attachments/assets/70a62b7a-a596-4651-b579-17cd4e55c706)

If you want more advanced syntax highlighting, you can enable [Gopls' `ui.semanticTokens` setting](https://github.com/golang/vscode-go/wiki/settings#uisemantictokens).
