### ISSUE TITLE
Same highlighting for struct variable and field

### ISSUE THREAD

**Issue by StringNick** [worlpaker/go-syntax#4]
Expected different color of struct variable name and field:
```go
type AppConfig struct {
	Brand              string         `json:"brand"`
	BundleID           string         `json:"bundleId"`
	AppName            string         `json:"appName"`
	Skin               string         `json:"skin"`
} 
var config AppConfig

	appConfig := AppConfig{
		Brand:              config.Brand,
		BundleID:           config.BundleID,
		AppName:            settings.AppName,
		Skin:               settings.Skin,
}
``` 
Behavior:
<img width="429" alt="image" src="https://github.com/worlpaker/go-syntax/assets/13052752/a2a85b76-d77b-485f-87a6-e9907db420c8">
Current behavior looks unreadble, is it possible to switch colors.

**Comment by worlpaker** [comment]
You can customize it from [VS Code - Customizing a Color Theme](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme).

Variable names in struct and struct initialization are already scoped as `"variable.other.property.go"`, I can consider changing struct initialization variables to `"variable.other.property.init.go"` but I think they should be same.

However, I think field variables in struct initialization (e.g., like foo variable in below), should be still `"variable.other.go"` since they mean to be variables.

## Scope

```go
// struct definition
type AppConfig struct {
    Brand string `json:"brand"`
    // Brand scoped as: "variable.other.property.go"
}

foo := "bar"

// struct initialization
appConfig := AppConfig{
    Brand: foo,
    // Brand scoped as: "variable.other.property.go"
    // foo scoped as: "variable.other.go"
}
```

**Hint:** You can inspect scope from the Command Palette with the `Developer: Inspect Editor Tokens and Scopes` command. Also, disable vscode-go extension before the inspection, since gopls' ui.semanticTokens is disabled it will not allow you to inspect go files.

## Example

For instance, if you want to change `"variable.other.property.go"` color to purple, add this customization to your [settings.json](https://code.visualstudio.com/docs/getstarted/settings#_settingsjson)

```json
 "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": [
          "variable.other.property.go"
        ],
        "settings": {
          "foreground": "#bd93f9"
        }
      }
    ]
  }
```

Then, your code should look like this:

**Dark+ Theme**
![example](https://github.com/worlpaker/go-syntax/assets/34960716/afc37f94-258d-45c5-93c3-a5219fea2bbb)

**Comment by StringNick** [comment]
Thank you, very much for fast respond, Yes, i am agree, but its more
```go
type Foo struct {
 Bar string
}

var a Foo
var f = Foo {
  Bar: a.Bar,
}
``` 
a and Bar same color, i mean about that, but in github highlighting they have different color variable a and property(field struct) Bar is different color, i looked at `Developer: Inspect Editor Tokens and Scopes`, they are both `variable.other.go`, maybe bar should be `variable.other.property.go` or something else (dont know textmate token names, can we just put it like `variable.other.struct.property.go`), so it can help to way more customise themes.

In vscode:
<img width="246" alt="image" src="https://github.com/worlpaker/go-syntax/assets/13052752/dcc62a2e-b9dd-41f8-97ae-9ecdab2a8c89">

So i dont know maybe its not good, but ur option improving read of code, but maybe possible to increase functionality.
For example in zed editor:
<img width="213" alt="image" src="https://github.com/worlpaker/go-syntax/assets/13052752/15ade443-d819-4f76-bfe1-e9b33862d02e">

**Comment by worlpaker** [comment]
Thanks for the nice explanation. Your request is reasonable, but I aim to keep the extension simple.

My approach is different from theirs, I believe my example above makes it easier to read the code.
If your variable is intended to be used as a variable, it should be highlighted as such. I might be wrong, but in real world examples, it is generally used like this:

```go
type AppConfig struct {
	Brand    string `json:"brand"`
	BundleID string `json:"bundleId"`
	AppName  string `json:"appName"`
	Skin     string `json:"skin"`
}

// declare them directly
config := AppConfig{
	Brand:    "foo",
	BundleID: "foo",
	AppName:  "foo",
	Skin:     "foo",
}

// exactly same here, since config it's already variable
// then their fields should be variable
appConfig := AppConfig{
	Brand:    config.Brand,
	BundleID: config.BundleID,
	AppName:  config.AppName,
	Skin:     config.Skin,
}
```

I am not familiar with the Zed editor, but on GitHub (this website), it highlights every variable after the '.' (dot).

**Example**

```go
this.is.test.example
```

**Comment by worlpaker** [comment]
Actually, why not :) I think there is no harm in adding support for this, and it's a good idea. Thanks for the suggestion.

I am thinking of highlighting them as `"variable.other.property.field.go"`, so you can customize more!

## Example

If you want to highlight them in the same color:

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": [
          "variable.other.property.go",
          "variable.other.property.field.go"
        ],
        "settings": {
          "foreground": "#ff79c6"
        }
      }
    ]
  },
```

Your code will look like this:

**Dark+ Theme**
![example](https://github.com/worlpaker/go-syntax/assets/34960716/4403da27-895d-4ef7-8b7f-a5b541538e85)



@StringNick, Let me know your thoughts. If everything is ok, I will add this in v0.5.1

**Comment by worlpaker** [comment]
I decided to add this customization in v0.5.1. However, local package and third-party imported variables/constants in the struct initialization will be scoped `"variable.other.property.field.go"` as well.

I think it's good to support this and let developers choose if they want to use it. I've already explained it in the tests, but I will also include the information here for clarity.

```go
type Bar struct{}

type AppConfig struct {
	Brand    string                 `json:"brand"`
	BundleID string                 `json:"bundleId"`
	AppName  string                 `json:"appName"`
	Skin     string                 `json:"skin"`
	Foo      *string                `json:"foo"`
	FooX     chan<- context.Context `json:"foox"`
	Ctx      context.Context        `json:"ctx"`
	Bar      Bar                    `json:"bar"`
	Barx     *Bar                   `json:"barx"`
	FooBar   *Bar                   `json:"foobar"`
	TimerFoo time.Duration          `json:"timerfoo"`
	TimerBar time.Duration          `json:"timerbar"`
}

config := AppConfig{
	Brand:    "foo",
	BundleID: "foo",
	AppName:  "foo",
	Skin:     "foo",
}

appConfig := AppConfig{
	Brand:    config.Brand,    // comment
	BundleID: config.BundleID, /* comment */
	AppName:  config.AppName,
	Skin:     config.Skin,
	Foo:      &config.Brand,
	FooX:     make(chan<- context.Context),
	Ctx:      context.TODO(),
	Bar:      Bar{},
	Barx:     &Bar{},
	FooBar:   new(Bar),

	// Local package and third-party imported variables/constants
	// will be scoped "variable.other.property.field.go" as well.
	// See the examples below:
	// Since "config.Brand" and "time.Second" are not different,
	// "Second" will be scoped as "variable.other.property.field.go" here.
	TimerFoo: time.Second,     // "Second" will be scoped as "variable.other.property.field.go"
	TimerBar: 5 * time.Second, // But in here, "Second" will be scoped as "variable.other.go"
}
```
