### ISSUE TITLE
Use as default Go grammar in VS Code

### ISSUE THREAD

**Issue by alexr00** [worlpaker/go-syntax#5]
👋 I maintain the built in grammars in VS Code. The Go grammar we're currently using hasn't been updated in a while, and I see that the grammar in https://github.com/worlpaker/go-syntax/blob/master/syntaxes/go.tmLanguage.json solves some known issues and generally highlights Go well. 

I'm planning to try out https://github.com/worlpaker/go-syntax/blob/master/syntaxes/go.tmLanguage.json as the default Go grammar in VS Code Insiders for month or two. If I don't hear much negative feedback from the community, I'd like to use the grammar in VS Code stable. 

@worlpaker, do you plan to maintain this grammar long term?

**Comment by worlpaker** [comment]
Hi @alexr00,

I'm actively using Go and planning to maintain this grammar long term.

I believe it generally works fine, but I'm open to feedback from the community.

**Comment by alexr00** [comment]
That's great to hear! If issues for the grammar come into the VS Code repo I'll copy them into https://github.com/worlpaker/go-syntax.
