### ISSUE TITLE
Useless `"patterns"` inside `"other_variables"`

### ISSUE THREAD

**Issue by RedCMD** [worlpaker/go-syntax#7]
`"patterns"` does not work when `"match"` is present
currently it doesn't do anything and can be removed
![image](https://github.com/worlpaker/go-syntax/assets/33529441/77d5a607-ef09-4707-bb58-1f9270948bc0)

https://github.com/worlpaker/go-syntax/blob/02bd7c945da893fdc9ec87db82eca176d4ff3432/syntaxes/go.tmLanguage.json#L2761-L2772

also the brackets in `"match"` can be removed `\\w+`

**Comment by worlpaker** [comment]
Thanks. Your details made it easy for me to review.
