### ISSUE TITLE
`"match"` doesn't work without `"patterns"` (inside `"captures"`)

### ISSUE THREAD

**Issue by RedCMD** [worlpaker/go-syntax#8]
if you want to retokenize `([\\s\\,\\w]+)` with `\\w+`
you need to place `"match"` inside a `"patterns": []` array
(or just add an empty `"patterns"` array, but that is not recommended)

![image](https://github.com/worlpaker/go-syntax/assets/33529441/78a02958-7466-4d63-8b60-27274527de45)

https://github.com/worlpaker/go-syntax/blob/02bd7c945da893fdc9ec87db82eca176d4ff3432/syntaxes/go.tmLanguage.json#L1860-L1869

**Comment by worlpaker** [comment]
Thanks!
