### ISSUE TITLE
`"patterns"` does not work directly inside `"beginCaptures"`

### ISSUE THREAD

**Issue by RedCMD** [worlpaker/go-syntax#9]
![image](https://github.com/worlpaker/go-syntax/assets/33529441/f5f63603-aeba-42f1-88ea-5e7524ed79d2)

https://github.com/worlpaker/go-syntax/blob/02bd7c945da893fdc9ec87db82eca176d4ff3432/syntaxes/go.tmLanguage.json#L1119-L1127

**Comment by worlpaker** [comment]
Thanks!
